### PR TITLE
Driven cavity tutorial

### PR DESCRIPTION
**Pull request by evoyiatzis**
I have created a simple tutorial for the driven cavity problem using the GUI for the incompressible Navier-Stokes module.
The problem is part of the NPARC Alliance Verification and Validation Archive and  it is described in more detail here https://www.grc.nasa.gov/www/wind/valid/cavity/cavity.html

### CODE REVIEW

**Comment by richb2k** [comment]
Hello,  your tutorial looks very nice.  It compiles into a pdf properly.  But, perhaps keeping the same style for the urls as shown in 'about.tex' would be better.  After going through the tutorial, adding each command as shown, and running the elmergui project, the contents look good.  
The other elmergui tutorials do not include a readme file, but if you want to add one, I'd suggest adding .md extension for readme.md.  
Lastly, after successfully running the tutorial, I was left wondering whether the Elmer solution was close numerically to the reference solution?  Maybe add SaveLine and save the vertical velocity profile and the horizontal velocity profile and compare the Elmer results to Table 1 and Table 2 in Ghia, etc.?

**Comment by richb2k** [comment]
Just to be clear, the PR could easily be accepted as is, without any changes.  The few suggestions are just suggestions.
Two more suggestions, the Ghia, etc., article uses second order elements, you could easily update the elmergrid file to use second order.   The results generated by Paraview are more difficult to compare to Ghia, perhaps generate the results using Isocontours in ElmerVTK?

**Comment by raback** [comment]
Ok, I take the judgement of Rich and merge. You may edit it later according to the suggestions, if you so desire. Thanx for the contribution!

**Comment by evoyiatzis** [comment]
Thanks for the suggestions/comments. 
I will remove the readme file (which is empty)and format the URLs asap

**Comment by richb2k** [comment]
Great.  I'm looking forward to your next tutorial!

**Comment by richb2k** [comment]
Using SaveLine and comparing the results for the Re 400 case, the results are very close.  Here are links to the contents of Table 1 and Table 2, which makes it easier to compare results:

[https://gist.github.com/ivan-pi/3e9326d18a366ffe6a8e5bfda6353219](url)
[https://gist.github.com/ivan-pi/caa6c6737d36a9140fbcf2ea59c78b3c](url)

**Pull request merged**
