### PR TITLE
The recent changes to Capacitance of Two Balls tutorial

### PR DESCRIPTION
**Pull request by richb2k**
attempted to fix the bibliography entry.  The change was  successful when compiling with TexWorks.  The change broke
 compiling using bash and 'source makedoc.sh', so trying to  build the full documenation will fail.  By making some changes,
 I was able to fix the 'source makedoc.sh' operation, but then  the bibliography entry did not properly build when compiling
 with TexWorks, and showed the same '?' instead of the biblio  entry.  Since this one tutorial is the only biblio entry in
 any of the pdf documents, it seems reasonable to remove the use  of biblio entirely, and instead create a footnote with the
 latest bibtex reference in the single tutorial, Capacitance of  Two Balls.  This PR makes all the needed changes to remove
 the use of bibliography from the tex files.

### CODE REVIEW

**Comment by richb2k** [comment]
Rewrote the section 'Multiple bodies from Salome to Elmer' in GetStartedElmer.pdf, with all new graphics, using Salome 9.7.0 and Elmer 9.0.   The rewrite was needed to reflect changes in Salome that occurred since 2009 when the original document was added to elmerfem wiki.

**Comment by richb2k** [comment]
Added a new section describing in detail how to use Gmsh to create a mesh for Elmer with multiple bodies, similar to the section on using Salome to create multiple bodies for use with Elmer.  Also created a new chapter, Elmer and External Tools, to hold both sections.  If at some point, someone creates a section using Freecad to create an Elmer mesh with multiple bodies, then they should add that section to this new chapter.

**Comment by richb2k** [comment]
Added short version of instructions about using Salome to create multiple bodies to be exported to Elmer.

**Comment by raback** [comment]
Nice work!

**Pull request merged**
