### PR TITLE
Synchronized directory and folder names.

### PR DESCRIPTION
**Pull request by richb2k**
This looks like a lot of changes, since several folders were renamed.  Renaming of course means to delete and add in github.  If this is too much at once, refuse the request and I'll resubmit in smaller pieces.  One benefit of renaming the 'tutorials-GUI-files' folder is that it became obvious that we are missing six ElmerGUI projects from six of the tutorials.

### CODE REVIEW

**Comment by richb2k** [comment]
Added two of the missing ElmerGUI projects, the ElasticHookNonlinear project, and FSI Obstacle project.  Animation videos for each were also added.

**Comment by richb2k** [comment]
Added the last two project folders to 'tutorials-GUI-files', Toy Glacier and Toy Glacier with Heat and Flow.  They run with ElmerGUI 9.0

**Comment by richb2k** [comment]
Updated Rayleigh Benard Instability tutorial, with graphics from Paraview.

**Comment by richb2k** [comment]
Converted the Radiation tutorial, now works with ElmerGUI 9.0

**Comment by raback** [comment]
Thank you! Looks good to me. Sorry for taking some time. It is great that the tutorials reflect the current version of the software. They were previously mainly not updated.

**Pull request merged**
