### PR TITLE
Add Get Started doc, and a tutorial template doc,

### PR DESCRIPTION
**Pull request by richb2k**
and a doc to help get started editing TeXworks document.

### CODE REVIEW

**Comment by raback** [comment]
Nice work! Get started may be useful for many. Note that the sf.net is not updated as frequently as the automated nightly builds under https://www.nic.funet.fi/pub/sci/physics/elmer/

**Comment by richb2k** [comment]
Thanks for merging this pr so quickly.  Looking at [https://www.nic.funet.fi/pub/sci/physics/elmer/doc/](url), it looks like the elmerfem-manuals haven't been updated since 22 January 2021.  Does that mean the docs aren't updated as part of the nightly build?  Or is that something that you need to trigger manually?

**Comment by raback** [comment]
Well, the manuals are updated manually. The reason is that they tend to change more slowly, and there hasn't been an insentive to set up the nightly build for those. I just did it for the public set.

**Comment by richb2k** [comment]
Okay, no problem with manual building of the manuals.  As you said, they shouldn't change much, so why add to nightly build.  Is it okay if I ask for you to trigger a manual build once in a while?  Once in a while would be, right after a PR of course!

**Pull request merged**
