### PR TITLE
Minor updates following suggestions from #31 

### PR DESCRIPTION
**Pull request by evoyiatzis**
Two small updates following suggestions from #31 

- Removing the readme file which is empty
- Formating in a consistent way the urls in the tutorial file

### CODE REVIEW

**Comment by richb2k** [comment]
Thanks for the updates, they look good and they compile fine too.

**Comment by evoyiatzis** [comment]
@richb2k feel free to include the figures comparing the obtained solution with the one presented in the work of Ghia

**Comment by richb2k** [comment]
@evoyiatzis if it's okay with you, I'll work on adding SaveLine and the results comparison to the ElmerGUI tutorial.  It will need to start off using 'New Project' to select the SaveLine solver from edf-extra.

**Comment by evoyiatzis** [comment]
@richb2k it is perfectly fine

**Pull request merged**
