### PR TITLE
Converted Acoustic Waves tutorial to ElmerGUI.  Works with Elmer 9.0.

### PR DESCRIPTION
**Pull request by richb2k**
As part of converting, it was necessary to load Elmer 6.2 with a working ElmerFront, which allowed running of the original tutorial.  A new domain.grd file was created to match the geometry of the original.  Results from ElmerPost were stored in 'tutorials-CL-files/AcousticWaves' folder.  The results from Paraview compare fairly well to the ElmerPost results, where Pressure-1 matches pressure-x, and Pressure-2 matches pressure-y.

### CODE REVIEW

**Comment by raback** [comment]
This is nice! ElmerFront is long obsolite and the code is not even distributed with Elmer. Hence there was no way to make the old tutorial.

**Comment by raback** [comment]
Btw, I did not write this tutorial. So those old tutorials without an author that you translate for ElmerGUI, maybe you can add your own name and N.N. if not known. Certainly not me. I've only done these GUI tutorials.

**Comment by richb2k** [comment]
Okay, I'll change it to 'original author not known', in the next PR.  I did that on a few of the other converted tutorials.

Regarding ElmerFront, I went to http://www.nic.funet.fi/pub/sci/physics/elmer/bin/history/Win2011/ and downloaded Elmer-svn5475-2011-12-16.exe.  Next, uninstall Elmer 9.0, and run that downloaded file to install Elmer 6.2.  When done, uninstall Elmer 6.2 and reinstall Elmer 9.0.  It only took a few minutes, and allowed me to run ElmerFront.

**Comment by richb2k** [comment]
Would you mind triggering another rebuild of the documenation?  Thanks,  Rich.

**Comment by raback** [comment]
These are now updated on nic.funet.fi and sf.net.

**Pull request merged**
